- name: configure user component
  hosts: user
  become: yes
  tasks:
  - name: disable default nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs:20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: create robosho system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: true
      home: /app

  - name: create app directory
    ansible.builtin.file:
      name: /app
      state: directory

  - name: download user code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
      dest: /tmp/user.zip
    
    # this module thinks file exist on ansible control server, need to extract on to remote machine
    # remote_src: yes means file alrady exits in user server
  - name: extract user code
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes

  - name: Install dependencies
    community.general.npm:
      path: /app

  - name: copy user service to syystem directory
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: systemctl deamon reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable user
    ansible.builtin.service:
      name: user
      state: started
      enabled: yes